### ISSUE TITLE
Show project list on people page

### ISSUE THREAD

**Issue by notionparallax** [notionparallax/ShadowWolf#511]

**Comment by Dawil** [comment]
person page

**Comment by Dawil** [comment]
Apparently this has been done it just stopped working long enough ago that we forgot about it. I knew I remembered following the breadcrumbs from project to person to project.

The code is in the following places:
* [beowulf service](https://github.com/notionparallax/ShadowWolf/blob/master/client/app/scripts/services/beowulf.js#L6)
* [person show controller](https://github.com/notionparallax/ShadowWolf/blob/master/client/app/scripts/controllers/people/show.js#L43)
* [person show view](https://github.com/notionparallax/ShadowWolf/blob/master/client/app/views/people/show_chunks/experience_.html#L4)

So I guess this issue is now a bugfix
