### ISSUE TITLE
images not linking to P&P

### ISSUE THREAD

**Issue by ryabsley** [notionparallax/ShadowWolf#598]
The following projects do not display images on P&P project sheets: 

B1976 MLC
B0707008
B0807502
Chris Clarke McKenzie Hse

A couple of them have two folders on Open Assets (usually one of which is empty).

**Comment by notionparallax** [comment]
This might require someone else to modify OA

**Comment by hinds89** [comment]
Project Number | Name | Comments |
---|---|---
B1976 MLC | MLC Fitout - Original fitout 1976 by Jon Voller | FIXED - Changed P&P project number to match Open Asset 
B0707008 | Watermark Apartment Refurbishments | changed project number on P&P - changed to just `B0707008` (instead of `B0707008 - was B0706513`)
B0807502 | Ergon Fitout Manual | Images seem to be working already when I go into this.  However have changed 'code' on Open Asset and Project Number on P&P to now be just `B0903007` (instead of `B0903007 (BD was B0807502)`)
Chris Clarke McKenzie Hse | McKenzie House | FIXED - Renamed project number on P&P to Chris_Clarke_McKenzie_Hse (to match Open Asset)
Chris Clarke StanstedAirportUK | Stansted Airport, United Kingdom | FIXED
Chris Clarke McLeod Hse | Clarke McLeod House | FIXED
Chris Clarke Hse Ascot | Clarke House, Ascot | FIXED

**Comment by hinds89** [comment]
Hmmm ... B0707008 still doesn't want to show images.  I suspect this is because there are two Open Asset projects with that code?

**Comment by hinds89** [comment]
Images in Open Asset for this project are against the wrong project, I have raised a support request, Request ID : 11942, with IDT to move the images and delete the project numbers from Open Asset.
