### ISSUE TITLE
project photos not showing in experience tab or person

### ISSUE THREAD

**Issue by notionparallax** [notionparallax/ShadowWolf#675]

**Comment by notionparallax** [comment]
dupe of #675

**Comment by Dawil** [comment]
In commit 228f95ad762a16cc4b6f140706a9916a9799985b I disabled refresh_hero_image in rails. After that openasset's old IP address became invalidated and we moved to using the domain name. I ran an update on the database data to upate the existing urls however because we removed refresh_hero_image that issue is still unresolved.

I'll close this issue now that the temporary fix has been made but I think I'll also create another issue for a more permanent solution to updating the hero images.
