### ISSUE TITLE
Pictures on Project Sheets out of order

### ISSUE THREAD

**Issue by hinds89** [notionparallax/ShadowWolf#775]
@Dawil @DanielMok
The project sheets aren't always selecting the pictures based on ranking of 10, 9 ,8 
For example see (ones that have pdfs as images?):
- [University of Melbourne Leicester Street Student Housing M1110004](http://phonelist.bvn.com.au:9000/#/projects/M1110004) 
- [Bendigo Bank Headquarters M031013](http://phonelist.bvn.com.au:9000/#/projects/M031013)
- [The King's School Sports Centre S050324](http://phonelist.bvn.com.au:9000/#/projects/S050324)
- [North West Rail Link Adjoining Lands Masterplan S1304007](http://phonelist.bvn.com.au:9000/#/projects/S1304007)

**Comment by hinds89** [comment]
@danielmok

**Comment by Dawil** [comment]
This is most likely due to the [`images_by_tag`](https://github.com/notionparallax/ShadowWolf/blob/oaf-revamp/oaf/app/models.rb#L8-L14) function in oaf/app/models.rb. At first I thought the call to `.reverse` was unnecessary but now that I look at it `tag_rank || 0` could also be problematic.

Either way this should be a pretty straightforward case of writing some failing unit tests then passing them.

**Comment by hinds89** [comment]
@Dawil I'm still having an issue with (ASB North Wharf S0910004)[http://phonelist.bvn.com.au:9000/#/projects/S0910004]

**Comment by hinds89** [comment]
It works now (I need to learn to click the mouse)
